
FROM node:18


WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application files
COPY . .


EXPOSE 3000

# Start the application
CMD ["node", "patient-service.js"]

